version: 1

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

flags:
  - -trimpath
  - -tags=netgo

goos: linux
goarch: amd64

main: ./cmd/rnexus
binary: rnexus-{{ .Os }}-{{ .Arch }}

ldflags:
  - "-X main.version={{ .Env.VERSION }}"
  - "-X main.buildDate={{ .Env.COMMIT_DATE }}"
  - "-X main.gitCommit={{ .Env.COMMIT }}"
